# Copyright (c) 2019-2021 kolpav <https://github.com/kolpav/purge-artifacts-action>
#
# expire-in
# Required for how long the artifacts should be kept.
# formats 10 minutes, 1hr 20mins, 7days, 1week
# Setting this to 0 will delete all artifacts
#

name: 'Delete old artifacts'
on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 18 * * *

jobs:  
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1days # Setting this to 0 will delete all artifacts
